/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/studio' | '/api/public/img'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio' | '/api/public/img'
  id: '__root__' | '/' | '/studio' | '/api/public/img'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
